config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do

  root   'sessions#new'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get   'add_admin'
      get   'remove_admin'
    end
    resources :mailing_lists, only: [:index, :show, :new, :create, :edit, :update] do
      member do
        get 'confirm'
        get 'send_ml'
        get 'applay_saved_ml'
        get 'destroy_saved_ml'
      end
    end
    resources :timetables, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      member do
        get 'confirm'
        get 'publish_timetable'
        get 'applay_saved_timetable'
        get 'destroy_saved_timetable'
        post 'reservation'
        delete 'delete_reservation'
      end
    end
  end

  resources :account_activations, only: [:edit, :create] do
    collection do
      get 'resend'
    end
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :notifications,       only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'creator'
    end
  end

  resources :accept_passes,       only: [:show, :edit, :update]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  before_action :prohibit_direct_access, only: [:applay_saved_timetable, :destroy_saved_timetable, :confirm]
  before_action :admin_user, only: [:new, :create, :edit, :destroy, :update, :applay_saved_timetable,
                :destroy_saved_timetable, :confirm]
  before_action :set_timetable, only: [:show, :edit, :update, :destroy_saved_timetable, :destroy,
                :confirm, :publish_timetable, :reservation]
  before_action :set_saved_timetables, only: [:new, :create, :edit, :update, :applay_saved_timetable, :destroy_saved_timetable]

  def index
    @timetables = Timetable.where(published: true).order(published_at: :desc).page(params[:page])
  end

  def show
    @timetable_date = "<th class='date'></th>"  # タイムテーブル左上の空セルを最初に登録
    @date_count = 0                               # 何日分のデータかを格納
    @timetable.from_date.upto(@timetable.to_date) do |date|
      @timetable_date += "<th class='center date'>#{(l date, format: :short)}</th>"
      @date_count += 1
    end
  end

  def new
    @timetable = current_user.timetables.build()
    @period_hash, @default_from_date, @default_to_date, @times = init_timetable_view(@timetable)  # viewの初期設定
  end

  def create
    @timetable = current_user.timetables.build(timetable_params)
    if @timetable.save
      timetable_confirm_and_template_process
    else
      flash.now[:danger] = "タイムテーブルの保存に失敗しました<br>もう一度実行してください"
      render :new
    end
  end

  def edit
    @period_hash, @default_from_date, @default_to_date, @times = init_timetable_view(@timetable)  # viewの初期設定
  end

  def update
    if @timetable.update_attributes(timetable_params)
      timetable_confirm_and_template_process
    else
      flash.now[:danger] = "タイムテーブルの保存に失敗しました<br>もう一度実行してください"
      render :edit
    end
  end

  def destroy
    @timetable.destroy
    redirect_to user_timetables_path(current_user)
  end

  def applay_saved_timetable
    @timetable = Timetable.find(params[:id]).dup # PATCHリクエストを送信しないようにdupでオブジェクトをコピーして新たに作成
    @period_hash, @default_from_date, @default_to_date, @times = init_timetable_view(@timetable)  # viewの初期設定
    flash.now[:info] = "選択したテンプレートを適用しました"
    render :new
  end

  def destroy_saved_timetable
    @timetable.destroy
    flash[:danger] = "選択したテンプレートを削除しました"
    redirect_to new_user_timetable_path(current_user)
  end

  def confirm
    @timetable_date = "<th></th>"  # タイムテーブル左上の空セルを最初に登録
    @space_cell = ""               # 空のセル
    @timetable.from_date.upto(@timetable.to_date) do |date|
      @timetable_date += "<th class='center'>#{(l date, format: :short)}</th>"
      @space_cell += "<td></td>"
    end
  end

  def publish_timetable
    @timetable.update_columns(published: true, published_at: Time.zone.now)
    flash[:info] = "タイムテーブルを作成しました"
    redirect_to user_timetable_path(current_user, @timetable)
  end

  def reservation
    @timetable_date = "<th></th>"  # タイムテーブル左上の空セルを最初に登録
    @date_count = 0                # 何日分のデータかを格納
    @timetable.from_date.upto(@timetable.to_date) do |date|
      @timetable_date += "<th class='center'>#{(l date, format: :short)}</th>"
      @date_count += 1
    end

    @reservation = current_user.reservations.build(reservation_params) # reservationテーブルにフォームの内容を格納
    flash[:danger] = "登録名は空白でない20文字以下の文字数で入力してください" unless @reservation.save

    redirect_to user_timetable_path(current_user, params[:id])
  end

  def delete_reservation
    Reservation.find(params[:del_id]).destroy if Reservation.exists?(params[:del_id])   # 削除するidを取得し、DBから予約を削除
    redirect_to user_timetable_path(current_user, params[:id])
  end

  private

    # ストロングパラメータの設定（タイムテーブルを作成）
    def timetable_params
      params.require(:timetable).permit(:from_date, :to_date, :times)
    end

    # ストロングパラメータの設定（タイムテーブルに登録）
    def reservation_params
      params.require(:reservation).permit(:timetable_id, :band_name, :resavation_date, :resavation_koma)
    end

    # タイムテーブルを作成する期間のセレクトボックス選択肢
    def create_timetable_period
      period_hash = Hash.new
      (Date.today - 2.weeks).upto(Date.today + 1.month) do |date|
        period_hash.store((l date, format: :short), date)
      end
      return period_hash
    end

    # from_dateの初期値を設定
    def set_default_from_date(from_date)
      if from_date.nil? || self.action_name == 'applay_saved_timetable' # newアクションからの呼び出された場合、またはapplay_saved_timetableアクションから呼び出された場合
        default_from_date = Date.today
      else                                                              # editアクションからの呼び出された場合
        default_from_date = from_date
      end
      return default_from_date
    end

    # to_dateの初期値を設定
    def set_default_to_date(to_date, from_date)
      if to_date.nil?                                         # newアクションからの呼び出された場合
        if Timetable.where(published: true).last.nil?         # 公開済みのタイムテーブルが存在しない場合
          default_to_date = Date.today + 6                    # 今日から６日後を指定
        else                                                  # 公開済みのタイムテーブルが存在する場合
          default_to_date = Date.today + (Timetable.where(published: true).last.to_date - Timetable.where(published: true).last.from_date)
        end
      elsif self.action_name == 'applay_saved_timetable'      # applay_saved_timetableアクションから呼び出された場合
        default_to_date = Date.today + (to_date - from_date)  # 今日からテンプレートで保存された日数後を指定
      else                                                    # editアクションからの呼び出された場合
        default_to_date = to_date
      end
      return default_to_date
    end

    # タイムテーブルの各コマ毎の時間を作成
    def set_koma_times(times)
      unless koma_times = times                       # timesが存在しない場合(newページの場合)
        if Timetable.where(published: true).last.nil? # 公開済みのタイムテーブルが存在しない場合
          koma_times = <<~'EOS'
            8:50~10:20
            10:20~12:30
            12:30~14:30
            14:30~16:10
            16:10~18:00
            18:00~20:00
            20:00~22:00
          EOS
        else                                          # 公開済みのタイムテーブルが存在する場合
          koma_times = Timetable.where(published: true).last.times
        end
      end
      return koma_times
    end

    # viewの初期値を設定
    def init_timetable_view(timetable)
      period_hash = create_timetable_period                           # 期間のセレクトボックス選択肢
      default_from_date = set_default_from_date(timetable.from_date)  # from_dateの初期値を設定
      default_to_date = set_default_to_date(timetable.to_date, timetable.from_date) # to_dateの初期値を設定
      times = set_koma_times(timetable.times)                         # 各コマ毎の時間の値
      return period_hash, default_from_date, default_to_date, times
    end

    def set_timetable
      if Timetable.exists?(params[:id])
        @timetable = Timetable.find(params[:id])
      else
        redirect_to root_path
      end
    end

    # カレントユーザが保存中のタイムテーブルを取得
    def set_saved_timetables
      @saved_timetables = current_user.timetables.where(saved: true).order(created_at: :desc) if user_saved_timetable?
    end

    # タイムテーブルの作成前確認とテンプレート保存の処理（newとeditで同じ処理のためまとめる）
    def timetable_confirm_and_template_process
      # エラー処理
      message = ""
      message += "期間が不正です<br>" if @timetable.from_date > @timetable.to_date            # to_dateがfrom_dateよりも過去のとき
      message += "各コマの時間を記入してください" if @timetable.times.chomp("").blank?        # 各コマの時間が空白のとき
      message += "各コマの時間は500字以内で記入してください" if 500 < @timetable.times.length # 各コマの時間は500字以上のとき
      unless message.blank?
        flash[:danger] = message
        redirect_back(fallback_location: root_path)
        return
      end

      if params[:commit_value] == "confirm"                           # 「確認」が実行された場合
        redirect_to confirm_user_timetable_path(current_user, @timetable)
      elsif params[:commit_value] == "template"                       # 「現在の内容を保存」が実行された場合
        if current_user.timetables.where(saved: true).count < 5       # タイムテーブル保存数が５件より少なければ
          @timetable.update_attribute(:saved, true)
          flash[:info] = "作成中のタイムテーブルをテンプレートとして保存しました<br>
                          次回以降いつでも呼び出して使用できます"
        else
          flash[:danger] = "保存可能なタイムテーブルは5件までです"
        end
        redirect_to new_user_timetable_path(current_user)
      else
        flash[:danger] = "不正な操作です"
        redirect_to root_path
      end
    end
end

app/helpers/timetables_helper.rb
module TimetablesHelper
  # ユーザーがタイムテーブルを保存していればtrue、その他ならfalseを返す
  def user_saved_timetable?
    current_user.timetables.exists?(saved: true)
  end
end

app/views/timetables/_new_edit_template.html.erb
<% provide(:title, 'タイムテーブル作成') %>
<div class="container create-timetable">

  <h1></h1>
  <h2>新しく作成するタイムテーブルの<br class="visible-xs">設定を行ってください<br>
  「期間」の間隔と「各コマの時間」は<br class="visible-xs">前回作成した内容を引き継ぎます</h2>

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      <%= form_for(@timetable, url: path, html: {id: 'timetable-form'}) do |f| %>
        <%= render 'shared/error_messages' %>

        <% if user_saved_timetable? %>
          <%= f.label :saved_timetable, "保存中のタームテーブル" %>
          <% @saved_timetables.each do |saved_timetable| %>
            <div class="index">
              <li>
                <table class="index-table">
                  <%= "<tr><th>期間の間隔</th><td>：</td><td>#{(saved_timetable.to_date - saved_timetable.from_date + 1).to_i}日間</td></tr>
                      <tr><th>各コマの時間</th><td>：</td><td>#{my_truncate(saved_timetable.times, 150)}</td></tr>".html_safe %>
                </table>
              <div class="small-btn float-left">
                <%= link_to "適用", applay_saved_timetable_user_timetable_path(current_user, saved_timetable), class: "btn btn-primary" %>
              </div>
              <div class="small-btn float-left">
                <%= link_to "削除", destroy_saved_timetable_user_timetable_path(current_user, saved_timetable), class: "btn btn-danger" %>
              </div>
              <div class="clear"></div>
            </li>
            </div>
          <% end %>
        <% end %>

        <%= f.label :from_date, "期間" %>

          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <%= f.select :from_date, options_for_select(@period_hash, selected: @default_from_date), {}, {class: 'form-control'} %>
            </div>
            <span class="form-str col-lg-4 col-md-4 col-sm-4 col-xs-4 select-interval">から</span>
          </div>

          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <%= f.select :to_date, options_for_select(@period_hash, selected: @default_to_date), {}, {class: 'form-control'} %>
            </div>
            <span class="form-str col-lg-4 col-md-4 col-sm-4 col-xs-4 select-interval">まで</span>
          </div>

        <%= f.label :times, "各コマの時間" %>
        <div class="label-note">
          <%= f.label :times, "コマ毎に改行して時間を記入してください", class: 'font-normal' %>
        </div>
        <%= f.text_area :times, rows: 10, value: @times, class: 'form-control' %>

        <%= hidden_field_tag :commit_value %>

        <div class="submit-btn">
          <%= f.submit "確認", onClick: ("return submit_with_value('timetable-form','confirm');"), class: 'btn btn-primary' %>
        </div>

        <%= f.submit "テンプレートとして保存", onClick: ("return submit_with_value('timetable-form','template');"), class: 'btn btn-info' %>
      <% end %>
    </div>
  </div>
</div>

app/views/timetables/_timetable.html.erb
<li>
  <table class="index-table">
    <%= "<tr><th>期間</th><td>：</td><td>#{(l timetable.from_date, format: :long)} - #{(l timetable.to_date, format: :short)}</td></tr>".html_safe %>
  </table>

  <span class="small-btn">
    <%= link_to "確認", user_timetable_path(current_user, timetable), class: "btn btn-primary" %>
  </span>
  <% if current_user.admin? %>
    <span class="small-btn">
      <%= link_to "削除", user_timetable_path(current_user, timetable), method: :delete,
                  data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger" %>
    </span>
  <% end %>
</li>

app/views/timetables/confirm.html.erb
<% provide(:title, 'タイムテーブル確認') %>
<div class="container">

  <h1></h1>
  <h2>この内容でよろしいですか？</h2>

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      <table class="timetable-confirm">
        <tr><%= @timetable_date.html_safe %></tr>
        <% @timetable.times.lines do |timetable_time| %>
          <% unless timetable_time.blank? %>
            <tr><th><%= my_truncate(timetable_time, 30) %></th><%= @space_cell.html_safe %></tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="submit-btn">
        <%= link_to "作成", publish_timetable_user_timetable_path(current_user, @timetable), class: "btn btn-block btn-primary" %>
      </div>
      <%= link_to "修正", edit_user_timetable_path(current_user, @timetable), class: "btn btn-block", id: "fix-btn" %>
    </div>
  </div>
</div>

app/views/timetables/edit.html.erb
<%= render 'new_edit_template', { path: user_timetable_path(current_user) } %>

app/views/timetables/index.html.erb
<% provide(:title, '過去のタイムテーブル') %>
<div class="container">
  <h1></h1>

  <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12 nopadding">
    <div class="center row">
      <%= paginate @timetables %>
    </div>

    <ul class="index row">
      <%= render @timetables %>
    </ul>

    <div class="center row">
      <%= paginate @timetables %>
    </div>
  </div>
</div><!-- container -->

app/views/timetables/new.html.erb
<%= render 'new_edit_template', { path: user_timetables_path(current_user) } %>

app/views/timetables/show.html.erb
<% provide(:title, 'タイムテーブル') %>
<dic class="timetable">
  <div class="container">
    <h1></h1>

    <div class="row">
      <div class="col-md-10 col-md-offset-2 col-xs-12" onLoad="FixedMidashi.create();">

          <div class="fixed-midashi">
            <table _fixedhead='rows:1; cols:1;'>
              <tr><%= @timetable_date.html_safe %></tr>

              <% @timetable.times.lines do |timetable_time| %>
                <% unless timetable_time.blank? %>
                  <tr>
                    <!-- タイムテーブルの左の時間部分 -->
                    <th class="koma"><%= my_truncate(timetable_time, 30) %></th>

                    <!-- タイムテーブルのデータ部分 -->
                    <% @date_count.times do |date_num| %>
                      <td>

                        <!-- タイムテーブルに登録されている場合 -->
                        <% if Reservation.exists?(timetable_id: params[:id], resavation_date: date_num, resavation_koma: timetable_time) %>
                          <% current_reservation = Reservation.find_by(timetable_id: params[:id], resavation_date: date_num, resavation_koma: timetable_time) %>

                          <!-- 登録名（バンド名） -->
                          <div class="band_name center">
                            <%= current_reservation.band_name %>
                          </div>

                          <!-- 登録者名 -->
                          <div class="reservation_user center">
                            <!-- 登録者が削除されている場合 -->
                            <% if deleted_user?(current_reservation.user) %>
                              登録：削除されたユーザ
                              <!-- 登録者が削除されていない場合 -->
                            <% else %>
                              登録：<%= link_to my_truncate(current_reservation.user.name, 25), current_reservation.user %>
                            <% end %>
                          </div>

                          <!-- 過去のタイムテーブルは編集不可 -->
                          <% if Timetable.count  == 1 || (Timetable.where(published: true).last.id == params[:id].to_i && Timetable.count != 1) %>

                            <!-- ログインしているユーザと練習登録者が一致、または管理者の場合は削除リンクを表示 -->
                            <% if current_reservation.user == current_user || current_user.admin == true %>
                              <!-- 登録削除のリンク -->
                              <div class="delete_link center">
                                <%= link_to "削除", delete_reservation_user_timetable_path(del_id: current_reservation.id), method: :delete,
                                    class: "btn btn-danger", data: { confirm: "「#{current_reservation.band_name}」を削除してよろしいですか？" }  %>
                              </div>
                            <% end %>

                          <% end %>

                        <!-- タイムテーブルに登録されていない場合 -->
                        <% else %>

                          <%= form_for(:reservation, url: reservation_user_timetable_path(current_user)) do |f| %>
                            <%= render 'shared/error_messages' %>

                            <!-- 過去のタイムテーブルは編集不可 -->
                            <% if Timetable.count  == 1 || (Timetable.where(published: true).last.id == params[:id].to_i && Timetable.count != 1) %>
                              <%= f.text_field :band_name, class: 'form-control' %>
                              <%= f.hidden_field :timetable_id, value: params[:id] %>
                              <%= f.hidden_field :resavation_date, value: date_num %>
                              <%= f.hidden_field :resavation_koma, value: timetable_time %>
                              <%= f.submit "練習をとる", class: "btn btn-primary" %>
                            <% end %>

                          <% end %>

                        <% end %>

                      </td>
                    <% end %>

                  </tr>
                <% end %>
              <% end %>
            </table>
          </div><!-- fixed_midashi -->

          <%= link_to "過去のタイムテーブルを確認するにはこちら", user_timetables_path(current_user) %>

      </div><!-- col -->
    </div><!-- row -->

  </div><!-- container -->
</div><!-- timetable -->