config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do

  root   'sessions#new'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get   'add_admin'
      get   'remove_admin'
    end
    resources :mailing_lists, only: [:index, :show, :new, :create, :edit, :update] do
      member do
        get 'confirm'
        get 'send_ml'
        get 'applay_saved_ml'
        get 'destroy_saved_ml'
      end
    end
    resources :timetables, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      member do
        get 'confirm'
        get 'publish_timetable'
        get 'applay_saved_timetable'
        get 'destroy_saved_timetable'
        post 'reservation'
        delete 'delete_reservation'
      end
    end
  end

  resources :account_activations, only: [:edit, :create] do
    collection do
      get 'resend'
    end
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :notifications,       only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'creator'
    end
  end

  resources :accept_passes,       only: [:show, :edit, :update]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/notification.rb
class Notification < ApplicationRecord

  # ページネーションでの１ページの表示数
  paginates_per 20
  
  validates :message, presence: true, length: { maximum: 5000 }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :logged_in_user,   only: [:index,:new, :create, :edit, :update, :destroy]
  before_action :sudo_user,        only: [:new, :create, :edit, :update, :destroy]
  before_action :set_notification, only: [:edit, :update, :destroy]

  def index
    @notifications = Notification.order(:created_at).reverse_order.page(params[:page])
    current_user.update_attribute(:checked_notification, true)  # お知らせページ表示でchecked_notificationをtrueに
  end

  def new
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(notification_params)
    if @notification.save
      users = User.where(activated: true)                     # アクティブなユーザーを取得
      users.each do |user|
        user.update_attribute(:checked_notification, false)   # 全ユーザーのchecked_notificationをfalseに
      end
      flash[:info] = 'お知らせを登録しました'
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @notification.update_attributes(notification_params)
      flash[:success] = 'お知らせを編集しました'
      redirect_to notifications_path
    else
      render :new
    end
  end

  def destroy
    @notification.destroy
    redirect_to notifications_path
  end

  def creator
  end

  private

    # ストロングパラメータの設定
    def notification_params
      params.require(:notification).permit(:message)
    end

    def set_notification
      if Notification.exists?(params[:id])
        @notification = Notification.find(params[:id])
      else
        redirect_to root_path
      end
    end

    # イトウかソネダのみ編集可能
    def sudo_user
      if current_user.id != 1 && current_user.id != 2
        redirect_to root_path
      end
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_new_edit_template.html.erb
<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12 nopadding">
  <%= form_for(@notification) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :message, "お知らせ内容" %>
    <%= f.text_area :message, rows: 5, class: 'form-control'  %>

    <%= f.submit "登録", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/notifications/_notification.html.erb
<li class="notification">

  <div class="bold">
    <%= notification.updated_at.strftime("%Y年%m月%d日") %>
  </div>
  
  <div class="content">
    <%= simple_format(h notification.message) %>
  </div>
  <% if current_user.id == 1 || current_user.id == 2 %>
    <div class="small-btn">
      <%= link_to "編集", edit_notification_path(notification), class: "btn btn-primary" %>
      <%= link_to "削除", notification_path(notification), method: :delete,
                data: {confirm: "「#{notification.updated_at.strftime("%Y年%m月%d日")}」の内容を削除してよろしいですか？"},
                class: "btn btn-danger" %>
    </div>
  <% end %>

</li>

app/views/notifications/creator.html.erb
<% provide(:title, '中の人') %>
<div class="container creator">
  <h1></h1>
  <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12 nopadding">
    
    <div class="flex">
      <%= image_tag 'ito.jpg', alt: 'ito', class: 'creator-img' %>
      <div class="flex col">
        <div class="name">
          <h2><%= link_to 'いとー', user_path(1) %></h2>
          <span>ホワイトボード作成</span>
        </div>
        <p class="text">
          軽音のせいで痛風になりました<br>
          ホワイトボードに何かあったら自分まで連絡ください
        </p>
      </div><!-- flex col -->
    </div><!-- flex -->

    <div class="flex">
      <%= image_tag 'soneda.jpg', alt: 'ito', class: 'creator-img' %>
      <div class="flex col">
        <div class="name">
          <h2><%= link_to 'そねだ', user_path(2) %></h2>
          <span>インフラ構築</span>
        </div>
        <p class="text">
          重いギターを膝の上に置いて弾くと前立腺炎になる
        </p>
      </div><!-- flex col -->
    </div><!-- flex -->

  </div><!-- col -->
</div><!-- container -->

app/views/notifications/edit.html.erb
<% provide(:title, 'お知らせ') %>
<div class="notification">
  <div class="container">
    <h1></h1>

    <%= render 'new_edit_template' %>
    
  </div>
</div>

app/views/notifications/index.html.erb
<% provide(:title, 'お知らせ') %>
<div class="container">
  <h1></h1>
  <h2 class="notification">更新情報など</h2>
  <p class="notification">ホワイトボードに何かあったときは<%= link_to '中の人', creator_notifications_path %>まで</p>

  <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12 nopadding">
    <% if current_user.id == 1 || current_user.id == 2 %>
      <%= link_to "お知らせを作成", new_notification_path, class: "new-notification" %>
    <% end %>

    <ul class="index">
      <%= render @notifications %>
    </ul>

    <div class="center">
      <%= paginate @notifications %>
    </div>

  </div><!-- col -->
</div><!-- container -->

app/views/notifications/new.html.erb
<% provide(:title, 'お知らせ') %>
<div class="notification">
  <div class="container">
    <h1></h1>

    <%= render 'new_edit_template' %>
    
  </div>
</div>