config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do

  root   'sessions#new'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get   'add_admin'
      get   'remove_admin'
    end
    resources :mailing_lists, only: [:index, :show, :new, :create, :edit, :update] do
      member do
        get 'confirm'
        get 'send_ml'
        get 'applay_saved_ml'
        get 'destroy_saved_ml'
      end
    end
    resources :timetables, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      member do
        get 'confirm'
        get 'publish_timetable'
        get 'applay_saved_timetable'
        get 'destroy_saved_timetable'
        post 'reservation'
        delete 'delete_reservation'
      end
    end
  end

  resources :account_activations, only: [:edit, :create] do
    collection do
      get 'resend'
    end
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :notifications,       only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'creator'
    end
  end

  resources :accept_passes,       only: [:show, :edit, :update]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/mailing_list.rb
class MailingList < ApplicationRecord
  # Userモデルとの関連付け
  belongs_to :user
  
  # ページネーションでの１ページの表示数
  paginates_per 10
  
  # バリデーション
  validates :from_name,  presence: true, length: { maximum: 50 }
  validates :title, length: { maximum: 255 }
  validates :to_graduated, acceptance: true, unless: proc {|a| a.to_enrolled? }
  validates :content,  presence: true, length: { maximum: 5000 }
  
  # サークルメールを送信(成功でtrue、失敗でfalseを返す)
  def send_circle_mail
    if self.to_enrolled && self.to_graduated  # 在校生・卒業生に送信する場合
      users = User.where(activated: true).where(mail_receive: true)
    elsif self.to_enrolled                    # 在校生のみに送信する場合
      users = User.where(activated: true).where(graduated: false).where(mail_receive: true)
    elsif self.to_graduated                   # 卒業生のみに送信する場合
      users = User.where(activated: true).where(graduated: true).where(mail_receive: true)
    else                                       # 送信できない場合
      return false
    end
    users.each do |user|  # user一人ずつに送信(本番環境では50人以上同時送信できないため)
      UserMailer.circle_mail(self, user).deliver_later
    end
    return true
  end
  
  # 3年以上前のメールを過去のメール一覧から削除(config/schedule.rbで設定)
  def delete_old_mails
    old_mails = MailingList.where(sent: true).where("sent_at < ?", 3.years.ago)
    old_mails.destroy unless old_mails.count == 0
  end
  
  # 1週間以上送信していないメールを削除(config/schedule.rbで設定)
  def delete_non_send_mails
    non_send_mails = MailingList.where(saved: false).where(sent: false).where("updated_at < ?", 7.days.ago)
    non_send_mails.destroy unless non_send_mails.count == 0
  end
end

app/controllers/mailing_lists_controller.rb
class MailingListsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  before_action :prohibit_direct_access, only: [:edit, :applay_saved_ml, :destroy_saved_ml, :confirm, :send_ml]
  before_action :set_mailing_list, only: [:show, :edit, :update, :destroy_saved_ml, :confirm, :send_ml]
  before_action :set_saved_mailing_lists, only: [:new, :create, :edit, :update, :applay_saved_ml, :destroy_saved_ml]
  
  def index
    @q = MailingList.search(params[:q])
    @mailing_lists = @q.result(distinct: true).where(sent: true).order(sent_at: :desc).page(params[:page])
  end
  
  def show
  end
  
  def new
    @mailing_list = current_user.mailing_lists.build()
    @mailing_list.from_name = current_user.name
  end
  
  def create
    @mailing_list = current_user.mailing_lists.build(mailing_list_params)
    if @mailing_list.save
      mail_confirm_and_template_process
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @mailing_list.update_attributes(mailing_list_params)
      mail_confirm_and_template_process
    else
      render :edit
    end
  end
  
  def applay_saved_ml
    @mailing_list = MailingList.find(params[:id]).dup # PATCHリクエストを送信しないようにdupでオブジェクトをコピーして新たに作成
    flash.now[:info] = "選択したテンプレートを適用しました"
    render :new
  end
  
  def destroy_saved_ml
    @mailing_list.destroy
    flash[:danger] = "選択したテンプレートを削除しました"
    redirect_to new_user_mailing_list_path(current_user)
  end

  def confirm
  end
  
  def send_ml
    @mailing_list.update_attribute(:title, "無題") if @mailing_list.title.blank?
    if @mailing_list.send_circle_mail
      @mailing_list.update_columns(sent: true, sent_at: Time.zone.now)
      flash[:info] = "サークルメールを送信しました"
    else
      flash[:danger] = "サークルメールを送信できませんでした"
    end
      redirect_to root_path
  end
  
  private

    # ストロングパラメータの設定
    def mailing_list_params
      params.require(:mailing_list).permit(:from_name, :title, :to_enrolled, :to_graduated, :content)
    end
    
    def set_mailing_list
      if MailingList.exists?(params[:id])
        @mailing_list = MailingList.find(params[:id])
      else
        redirect_to root_path
      end
    end
    
    # カレントユーザが保存中のメールを取得
    def set_saved_mailing_lists
      @saved_mailing_lists = current_user.mailing_lists.where(saved: true).order(created_at: :desc) if user_saved_mail?
    end
    
    # メールの送信前確認とテンプレート保存の処理（newとeditで同じ処理のためまとめる）
    def mail_confirm_and_template_process
      if params[:commit_value] == "confirm"                           # 「確認」が実行された場合
        redirect_to confirm_user_mailing_list_path(current_user, @mailing_list)
      elsif params[:commit_value] == "template"                       # 「現在の内容を保存」が実行された場合
        if current_user.mailing_lists.where(saved: true).count < 5    # メール保存数が５件より少なければ
          @mailing_list.update_attribute(:title, "無題") if @mailing_list.title.blank?
          @mailing_list.update_attribute(:saved, true)
          flash[:info] = "作成中のメールをテンプレートとして保存しました<br>
                          次回以降いつでも呼び出して使用できます"
        else
          flash[:danger] = "保存可能なメールは5件までです"
        end
        redirect_to new_user_mailing_list_path(current_user)
      else          
        flash[:danger] = "不正な操作です"
        redirect_to root_path
      end
    end
end

app/helpers/mailing_lists_helper.rb
module MailingListsHelper
  # メール作成時の複数行の改行表示に対応
  def apply_multiple_br(target)
    target = html_escape(target)
    target.gsub(/\r\n|\r|\n/, "<br>")
  end
  
  # ユーザーがメールを保存していればtrue、その他ならfalseを返す
  def user_saved_mail?
    current_user.mailing_lists.exists?(saved: true)
  end
end

app/views/mailing_lists/_confirm_show_template.html.erb
<p>
  <%= label :from_name, "名前" %>
  <div class="confirm-text"><%= link_to @mailing_list.from_name, @mailing_list.user %></div>
</p>

<p>
  <%= label :title, "メールタイトル" %>
  <% if @mailing_list.title.blank? %>
    <div class="confirm-text">無題</div>
  <% else %>
    <div class="confirm-text"><%= @mailing_list.title %></div>
  <% end %>
</p>

<p>
  <%= label :send_to, "メール送信先" %>
  <div class="confirm-text">
    <% if @mailing_list.to_enrolled && @mailing_list.to_graduated %>
      在校生・卒業生
    <% elsif @mailing_list.to_enrolled %>
      在校生
    <% elsif @mailing_list.to_graduated  %>
      卒業生
    <% else %> <!-- この分岐条件はありえないはずだけど一応書いてます -->
      送信先を選択してください
    <% end %>
  </div>
</p>

<p>
  <%= label :text, "メール本文" %>
  <div class="confirm-text"><%= apply_multiple_br(@mailing_list.content).html_safe %></div>
</p>

app/views/mailing_lists/_mailing_list.html.erb
<li>
  <table class="index-table">
    <%= "<tr><th>送信日時</th><td>：</td><td>#{(l mailing_list.sent_at, format: :long)}</td></tr>
         <tr><th>送信者</th><td>：</td><td>#{link_to mailing_list.from_name, mailing_list.user}</td></tr>
         <tr><th>タイトル</th><td>：</td><td>#{my_truncate(mailing_list.title, 50)}</td></tr>
         <tr><th>本文</th><td>：</td><td>#{my_truncate(mailing_list.content, 200)}</td></tr>".html_safe %>
  </table>

  <div class="small-btn">
    <%= link_to "確認", user_mailing_list_path(current_user, mailing_list), class: "btn btn-primary" %>
  </div>
</li>

app/views/mailing_lists/_new_edit_template.html.erb
<% provide(:title, 'メール作成') %>
<div class="container">
  <h1></h1>

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      <%= form_for(@mailing_list, url: path ,html: {id: 'ml-form'}) do |f| %>
        <%= render 'shared/error_messages' %>

        <% if user_saved_mail? %>
          <%= f.label :saved_mail, "保存中のメール" %>
          <% @saved_mailing_lists.each do |saved_mailing_list| %>
            <div class="index">
              <li>
                <table class="index-table">
                  <%= "<tr><th>保存日時</th><td>：</td><td>#{(l saved_mailing_list.created_at, format: :long)}</td></tr>
                      <tr><th>送信者</th><td>：</td><td>#{h(saved_mailing_list.from_name)}</td></tr>
                      <tr><th>タイトル</th><td>：</td><td>#{my_truncate(saved_mailing_list.title, 75)}</td></tr>
                      <tr><th>本文</th><td>：</td><td>#{my_truncate(saved_mailing_list.content, 75)}</td></tr>".html_safe %>
                </table>
              <div class="small-btn float-left">
                <%= link_to "適用", applay_saved_ml_user_mailing_list_path(current_user, saved_mailing_list), class: "btn btn-primary" %>
              </div>
              <div class="small-btn float-left">
                <%= link_to "削除", destroy_saved_ml_user_mailing_list_path(current_user, saved_mailing_list), class: "btn btn-danger" %>
              </div>
              <div class="clear"></div>
            </li>
            </div>
          <% end %>
        <% end %>

        <%= f.label :from_name, "名前" %>
        <%= f.text_field :from_name, class: 'form-control' %>

        <%= f.label :title, "メールタイトル" %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :send_to, "メール送信先" %>
        <div id="sendto_checkbox">
          <div class="checkbox-inline">
            <%= f.check_box :to_enrolled %> <%= f.label :to_enrolled, "在校生", class: 'font-normal' %>
          </div>
          <div class="checkbox-inline">
            <%= f.check_box :to_graduated %> <%= f.label :to_graduated, "卒業生", class: 'font-normal' %>
          </div>
        </div>

        <div class="content">
          <%= f.label :content, "メール本文" %>
          <%= f.text_area :content, rows: 10, class: 'form-control' %>
        </div>

        <%= hidden_field_tag :commit_value %>

        <div class="submit-btn">
          <%= f.submit "確認", onClick: ("return submit_with_value('ml-form','confirm');"), class: 'btn btn-primary' %>
        </div>

        <%= f.submit "テンプレートとして保存", onClick: ("return submit_with_value('ml-form','template');"), class: 'btn btn-info' %>

      <% end %>

      <div id="past-ml">
        <%= link_to "過去のメールを確認するにはこちら", user_mailing_lists_path(current_user) %>
      </div>
    </div>
  </div>
</div>

app/views/mailing_lists/confirm.html.erb
<% provide(:title, 'メール確認') %>
<h1></h1>
<h2>この内容でよろしいですか？</h2>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">

      <%= render 'confirm_show_template' %>

      <div class="submit-btn">
        <%= link_to "送信", send_ml_user_mailing_list_path(current_user, @mailing_list), class: "btn btn-block btn-primary" %>
      </div>
      <%= link_to "修正", edit_user_mailing_list_path(current_user, @mailing_list), class: "btn btn-block", id: "fix-btn" %>
    </div>
  </div>
</div><!-- container -->

app/views/mailing_lists/edit.html.erb
<%= render 'new_edit_template', { path: user_mailing_list_path(current_user) } %>

app/views/mailing_lists/index.html.erb
<% provide(:title, '過去のメール') %>
<div class="container">

  <h1></h1>

  <!-- 検索フォーム -->
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      <%= search_form_for(@q, url: user_mailing_lists_path(current_user)) do |f| %>
        <%= f.search_field :from_name_or_title_or_content_cont, class: 'form-control', placeholder: "検索キーワードを入力してください" %>
        <%= f.submit '検索', class: "btn btn-primary"  %>
      <% end %>
    </div>
  </div><!-- row -->

  <div class="center row">
    <%= paginate @mailing_lists %>
  </div>

  <ul class="index row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12 nopadding">
      <%= render @mailing_lists %>
    </div>
  </ul>

  <div class="center row">
    <%= paginate @mailing_lists %>
  </div>

</div><!-- container -->

app/views/mailing_lists/new.html.erb
<%= render 'new_edit_template', { path: user_mailing_lists_path(current_user) } %>

app/views/mailing_lists/show.html.erb
<% provide(:title, '過去のメール') %>
<h1></h1>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">

      <p>
        <%= label :created_at, "送信日時" %>
        <div class="confirm-text"><%= (l @mailing_list.created_at, format: :long) %></div>
      </p>

      <%= render 'confirm_show_template' %>

      <%= link_to "戻る", :back, class: "btn btn-block btn-primary" %>
    </div>
  </div> <!-- row -->
</div><!-- container -->