config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do

  root   'sessions#new'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get   'add_admin'
      get   'remove_admin'
    end
    resources :mailing_lists, only: [:index, :show, :new, :create, :edit, :update] do
      member do
        get 'confirm'
        get 'send_ml'
        get 'applay_saved_ml'
        get 'destroy_saved_ml'
      end
    end
    resources :timetables, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      member do
        get 'confirm'
        get 'publish_timetable'
        get 'applay_saved_timetable'
        get 'destroy_saved_timetable'
        post 'reservation'
        delete 'delete_reservation'
      end
    end
  end

  resources :account_activations, only: [:edit, :create] do
    collection do
      get 'resend'
    end
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :notifications,       only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'creator'
    end
  end

  resources :accept_passes,       only: [:show, :edit, :update]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="center">
    &copy; 2017 KIT WhiteBoard
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <div class="row">
    <div class="col-xs-10">
      <% if logged_in? && current_user.admin? %>
        <%= link_to "WhtieBoard<span id='admin-sign'>Admin</span>".html_safe, root_path, id: "logo" %>
      <% else %>
        <%= link_to "WhtieBoard".html_safe, root_path, id: "logo" %>
      <% end %>
    </div>
    <nav>
      <div class="nav navbar-nav navbar-right">
        <label class="toggle" for="open">
          <div id="sm-menu-icon" onClick="open_menu();"><span></span><span></span><span></span></div>
          <% if logged_in? %>
            <% unless current_user.checked_notification? %>
              <div class="notice"></div>
            <% end %> 
          <% end %>
        </label>
        <input id="open" type="checkbox" autocomplete="off">
        <div id="menu">
          <nav>
            <ul>
              <% if logged_in? %>
                <% unless Timetable.where(published: true).last.nil? %>
                  <li><%= link_to "タイムテーブル", user_timetable_path(current_user, Timetable.where(published: true).last), class: 'timetable' %></li>
                <% end %>
                <% if current_user.admin? %>
                  <li><%= link_to "タイムテーブル作成", new_user_timetable_path(current_user), class: 'create-timetable' %></li>
                <% end %>
                <li><%= link_to "サークルメール", new_user_mailing_list_path(current_user), class: 'mail' %></li>
                <li><%= link_to "サークルメンバー", users_path, class: 'member'%></li>
                <li><%= link_to "プロフィール", current_user, class: 'profile' %></li>
                <% if current_user.admin? %>
                  <li><%= link_to "承認パスワード設定", accept_pass_path(1), class: 'accept-pass' %></li>
                <% end %>
                <li class="notification">
                  <%= link_to "お知らせ", notifications_path, class: 'notification'%>
                  <% unless current_user.checked_notification? %>
                    <div class="notice"></div>
                  <% end %> 
                </li>
                <li><%= link_to "ログアウト", logout_path, method: "delete", class: 'logout' %></li>
              <% else %>
                <li><%= link_to "ログイン", login_path, class: 'login' %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </nav>
  </div><!-- row -->
  </div><!-- container -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow,noarchive" />
    
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <!-- ヘッダーを表示 -->
    <%= render 'layouts/header' %>
      
      <!-- フラッシュを表示-->
      <% flash.each do |message_type, message| %>
        <div class="flash-alert alert-<%= message_type %>"><%= message.html_safe %></div> <!-- html形式で出力 -->
      <% end %>
      
      <%= yield %>
      
      <!-- フッターを表示-->
      <%= render 'layouts/footer' %>
      
      <!-- 開発環境でデバック情報を表示-->
      <%= debug(params) if Rails.env.development? %>

  </body>
</html>